server:
  port: 8763

spring:
  application:
    name: spring-cloud-consul-producer2
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        serviceName: service-producer2


